#!/bin/sh
if [ "$(id -u)" = "0" ]; then
    printf 'grur: must not be run as root\n' >&2
    exit 1
fi
case "$1" in
  -m|--menu)
    shift
    exec python -B fzftui "$@"
    ;;
  -a|--aur)
    shift
    exec python -B grimaur "$@"
    ;;
  *)
    exec python -B gpmrap "$@"
    ;;
esac
